### PR TITLE
add lang file for tasks.js

### PR DESCRIPTION
**Pull request by maxinglo**

### CODE REVIEW

**Comment by DanielSurf10** [comment]
Hi @maxinglo,

Thank you for your pull request! Before I review and merge it, could you please provide a brief description of the changes you made? This will help me understand your contributions better and ensure a smooth review process.

Best regards,
DanielSurf

**Comment by maxinglo** [comment]
> Hi @maxinglo,
> 
> Thank you for your pull request! Before I review and merge it, could you please provide a brief description of the changes you made? This will help me understand your contributions better and ensure a smooth review process.
> 
> Best regards,
> DanielSurf

Dear DanielSurf,

I recently submitted a pull request with the following code changes:

Modified the quest item submission text to utilize the "getName()" function for retrieving the required item's name.
Provided i18n support to ensure proper localization of the displayed text.

Thank you for your time and consideration.

Best regards,
Maxinglo

**Comment by maxinglo** [comment]
I would like to offer my assistance in i18nizing all the content added through kubejs, if necessary.

**Comment by DanielSurf10** [comment]
Hi @maxinglo,

Thank you for explaining the changes you made, and I'm grateful for your contributions!

There's just one small adjustment needed: the quest "The Trade Market" needs some modifications in the "quest.snbt" file (not sure why it was named that way either!). Don't worry, I'll explain the steps to fix it later when you're ready to play the game.

**Pull request merged**
