### PR TITLE
I18n localization for tradecard

### PR DESCRIPTION
**Pull request by maxinglo**
Added language keys for localizing trade card text.

### CODE REVIEW

**Comment by DanielSurf10** [comment]
Great job, @maxinglo.
Then, add a feedback to document it so that if we need to review, it will be easier, okay?
Try to do this in the next pull requests.

**Comment by DanielSurf10** [comment]
I will do some quests from the "The Trade Market" tab, then you can see how I did it, and if you understand, you can do the rest.
But basically, you need to take the item's name and use a tellraw generator to translate and attach text together.

You can use a tellraw generator like this one: "[https://www.minecraftjson.com/]()".

Currently, the title and description are hardcoded strings like this:

image

As an example, there's one where 16 dirt costs 2 silver.
However, the title "Dirt" and the subtitle "Silver" need to be translated. 
The name needs to be the full name, also known as the fully qualified name, of the block, item, or whatever it is. It should be exactly the same as it is in the JSON file.
In the generator, you can do that one by one like this:

image

Then, you just place "["","16x ",{"translate":"block.minecraft.dirt"}]" here:

image
image

And it will work.

image

If you can, please do the same for the subtitle.

image

I hope you understood, if you have any questions, feel free to contact me.
I will make a commit with some changes so that you can have an idea. 
But if you didn't understand, no worries, I'll do it myself.
You can also do it directly in the "quests.snbt" file, but it's a different notation. It's there in the commit.

**Comment by maxinglo** [comment]
Dear @DanielSurf10 ,

Apologies for the oversight in my previous pull request. As a first-time collaborator on GitHub, I was unsure about the proper procedures. Thank you for bringing it to my attention.

I appreciate your feedback and will ensure to include clear descriptions in all my future pull requests. Your guidance is valuable, and I'm grateful for the opportunity to contribute to this project.

Best regards

**Comment by DanielSurf10** [comment]
Great job, @maxinglo. Don't worry, we're learning together.

**Pull request merged**
